- integrated master map parsing into daemon.   - fixed several brakages from above.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MOUNT HAVE_MOUNT UMOUNT HAVE_UMOUNT E2FSCK HAVE_E2FSCK E3FSCK HAVE_E3FSCK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBNSL LIBRESOLV HAVE_HESIOD LIBHESIOD HESIOD_FLAGS CPP EGREP HAVE_NISPLUS LDAP_FLAGS HAVE_LDAP LIBLDAP DAEMON_CFLAGS DAEMON_LDFLAGS initdir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS initdir confdir mapdir DMALLOCLIB MOUNT HAVE_MOUNT UMOUNT HAVE_UMOUNT E2FSCK HAVE_E2FSCK E3FSCK HAVE_E3FSCK MODPROBE HAVE_MODPROBE LEX PATH_LEX YACC PATH_YACC RANLIB PATH_RANLIB RPCGEN PATH_RPCGEN CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBNSL LIBRESOLV HAVE_HESIOD LIBHESIOD HESIOD_FLAGS CPP EGREP HAVE_NISPLUS LDAP_FLAGS HAVE_LDAP LIBLDAP DAEMON_CFLAGS DAEMON_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -841,15 +841,18 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
---disable-ext-env          disable search in environment for substitution variable
---disable-mount-locking          disable use of locking when spawning mount command
+  --disable-ext-env	  disable search in environment for substitution variable
+  --disable-mount-locking disable use of locking when spawning mount command
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
---with-path=PATH	  look in PATH for binaries needed by the automounter
---with-hesiod=DIR	  enable Hesiod support (libs and includes in DIR)
---with-openldap=DIR	  enable OpenLDAP map support (libs and includes in DIR)
+  --with-path=PATH	  look in PATH for binaries needed by the automounter
+  --with-mapdir=PATH	  look in PATH for mount maps used by the automounter
+  --with-dmalloc          use dmalloc, as in
+			  http://www.dmalloc.com/dmalloc.tar.gz
+  --with-hesiod=DIR	  enable Hesiod support (libs and includes in DIR)
+  --with-openldap=DIR	  enable OpenLDAP map support (libs and includes in DIR)
 
 Some influential environment variables:
   CC          C compiler command
@@ -1311,6 +1314,107 @@ echo "$as_me:$LINENO: result: $searchpath" >&5
 echo "${ECHO_T}$searchpath" >&6
 
 #
+# Location of init.d directory?
+#
+if test -z "$initdir"; then
+  echo "$as_me:$LINENO: checking location of the init.d directory" >&5
+echo $ECHO_N "checking location of the init.d directory... $ECHO_C" >&6
+  for init_d in /etc/init.d /etc/rc.d/init.d; do
+    if test -z "$initdir"; then
+      if test -d "$init_d"; then
+	initdir="$init_d"
+	echo "$as_me:$LINENO: result: $initdir" >&5
+echo "${ECHO_T}$initdir" >&6
+      fi
+    fi
+  done
+fi
+
+
+#
+# Location of system config script directory?
+#
+if test -z "$confdir"; then
+  echo "$as_me:$LINENO: checking location of the configuration defaults directory" >&5
+echo $ECHO_N "checking location of the configuration defaults directory... $ECHO_C" >&6
+  for conf_d in /etc/sysconfig /etc/defaults /etc/conf.d; do
+    if test -z "$confdir"; then
+      if test -d "$conf_d"; then
+	confdir="$conf_d"
+	echo "$as_me:$LINENO: result: $confdir" >&5
+echo "${ECHO_T}$confdir" >&6
+      fi
+    fi
+  done
+fi
+
+
+#
+# The user can specify --with-mapsdir=PATH to specify autofs maps go
+#
+if test -z "$mapdir"; then
+  echo "$as_me:$LINENO: checking location of the autofs maps directory" >&5
+echo $ECHO_N "checking location of the autofs maps directory... $ECHO_C" >&6
+  for map_d in /etc/autofs /etc; do
+    if test -z "$mapdir"; then
+      if test -d "$map_d"; then
+	mapdir="$map_d"
+	echo "$as_me:$LINENO: result: $mapdir" >&5
+echo "${ECHO_T}$mapdir" >&6
+      fi
+    fi
+  done
+fi
+
+# Check whether --with-mapdir or --without-mapdir was given.
+if test "${with_mapdir+set}" = set; then
+  withval="$with_mapdir"
+  if test -z "$withval" -o "$withval" = "yes" -o "$withval" = "no"
+	then
+		:
+	else
+		mapdir="${withval}"
+	fi
+
+fi;
+
+echo "$as_me:$LINENO: checking for autofs maps directory" >&5
+echo $ECHO_N "checking for autofs maps directory... $ECHO_C" >&6
+echo "$as_me:$LINENO: result: $mapdir" >&5
+echo "${ECHO_T}$mapdir" >&6
+
+
+#
+# Optional include dmalloc
+#
+echo "$as_me:$LINENO: checking if malloc debugging is wanted" >&5
+echo $ECHO_N "checking if malloc debugging is wanted... $ECHO_C" >&6
+
+# Check whether --with-dmalloc or --without-dmalloc was given.
+if test "${with_dmalloc+set}" = set; then
+  withval="$with_dmalloc"
+  if test "$withval" = yes; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_DMALLOC 1
+_ACEOF
+
+  DMALLOCLIB="-ldmallocth"
+  LDFLAGS="$LDFLAGS -g"
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi;
+
+
+
+#
 # Programs needed for various system functions or modules
 #
 for ac_prog in mount
@@ -1553,6 +1657,295 @@ _ACEOF
   HAVE_E3FSCK=1
 else
   HAVE_E3FSCK=0
+fi
+
+for ac_prog in modprobe
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_MODPROBE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MODPROBE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MODPROBE="$MODPROBE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $searchpath
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_MODPROBE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+MODPROBE=$ac_cv_path_MODPROBE
+
+if test -n "$MODPROBE"; then
+  echo "$as_me:$LINENO: result: $MODPROBE" >&5
+echo "${ECHO_T}$MODPROBE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$MODPROBE" && break
+done
+
+if test -n "$MODPROBE"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MODPROBE 1
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define PATH_MODPROBE "$MODPROBE"
+_ACEOF
+
+  HAVE_MODPROBE=1
+else
+  HAVE_MODPROBE=0
+fi
+
+
+for ac_prog in flex lex
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_LEX+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LEX in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LEX="$LEX" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $searchpath
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_LEX="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+LEX=$ac_cv_path_LEX
+
+if test -n "$LEX"; then
+  echo "$as_me:$LINENO: result: $LEX" >&5
+echo "${ECHO_T}$LEX" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$LEX" && break
+done
+
+if test -n "$LEX"; then
+
+cat >>confdefs.h <<_ACEOF
+#define PATH_LEX "$LEX"
+_ACEOF
+
+  PATH_LEX="$LEX"
+else
+  { { echo "$as_me:$LINENO: error: required program LEX not found" >&5
+echo "$as_me: error: required program LEX not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+for ac_prog in bison
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_YACC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $YACC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_YACC="$YACC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $searchpath
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_YACC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+YACC=$ac_cv_path_YACC
+
+if test -n "$YACC"; then
+  echo "$as_me:$LINENO: result: $YACC" >&5
+echo "${ECHO_T}$YACC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$YACC" && break
+done
+
+if test -n "$YACC"; then
+
+cat >>confdefs.h <<_ACEOF
+#define PATH_YACC "$YACC"
+_ACEOF
+
+  PATH_YACC="$YACC"
+else
+  { { echo "$as_me:$LINENO: error: required program YACC not found" >&5
+echo "$as_me: error: required program YACC not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+for ac_prog in ranlib
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_RANLIB+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $RANLIB in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_RANLIB="$RANLIB" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $searchpath
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_RANLIB="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+RANLIB=$ac_cv_path_RANLIB
+
+if test -n "$RANLIB"; then
+  echo "$as_me:$LINENO: result: $RANLIB" >&5
+echo "${ECHO_T}$RANLIB" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RANLIB" && break
+done
+
+if test -n "$RANLIB"; then
+
+cat >>confdefs.h <<_ACEOF
+#define PATH_RANLIB "$RANLIB"
+_ACEOF
+
+  PATH_RANLIB="$RANLIB"
+else
+  { { echo "$as_me:$LINENO: error: required program RANLIB not found" >&5
+echo "$as_me: error: required program RANLIB not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+for ac_prog in rpcgen
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_RPCGEN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $RPCGEN in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_RPCGEN="$RPCGEN" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $searchpath
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_RPCGEN="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+RPCGEN=$ac_cv_path_RPCGEN
+
+if test -n "$RPCGEN"; then
+  echo "$as_me:$LINENO: result: $RPCGEN" >&5
+echo "${ECHO_T}$RPCGEN" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RPCGEN" && break
+done
+
+if test -n "$RPCGEN"; then
+
+cat >>confdefs.h <<_ACEOF
+#define PATH_RPCGEN "$RPCGEN"
+_ACEOF
+
+  PATH_RPCGEN="$RPCGEN"
+else
+  { { echo "$as_me:$LINENO: error: required program RPCGEN not found" >&5
+echo "$as_me: error: required program RPCGEN not found" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
@@ -4284,24 +4677,6 @@ rm -f pietest.c
 
 
 #
-# Location of init.d directory?
-#
-if test -z "$initdir"; then
-  echo "$as_me:$LINENO: checking location of the init.d directory" >&5
-echo $ECHO_N "checking location of the init.d directory... $ECHO_C" >&6
-  for init_d in /etc/init.d /etc/rc.d/init.d; do
-    if test -z "$initdir"; then
-      if test -d "$init_d"; then
-	initdir="$init_d"
-	echo "$as_me:$LINENO: result: $initdir" >&5
-echo "${ECHO_T}$initdir" >&6
-      fi
-    fi
-  done
-fi
-
-
-#
 # Enable ability to access value in external env variable
 #
 # Check whether --enable-ext-env or --disable-ext-env was given.
@@ -4899,6 +5274,10 @@ s,@ECHO_C@,$ECHO_C,;t t
 s,@ECHO_N@,$ECHO_N,;t t
 s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
+s,@initdir@,$initdir,;t t
+s,@confdir@,$confdir,;t t
+s,@mapdir@,$mapdir,;t t
+s,@DMALLOCLIB@,$DMALLOCLIB,;t t
 s,@MOUNT@,$MOUNT,;t t
 s,@HAVE_MOUNT@,$HAVE_MOUNT,;t t
 s,@UMOUNT@,$UMOUNT,;t t
@@ -4907,6 +5286,16 @@ s,@E2FSCK@,$E2FSCK,;t t
 s,@HAVE_E2FSCK@,$HAVE_E2FSCK,;t t
 s,@E3FSCK@,$E3FSCK,;t t
 s,@HAVE_E3FSCK@,$HAVE_E3FSCK,;t t
+s,@MODPROBE@,$MODPROBE,;t t
+s,@HAVE_MODPROBE@,$HAVE_MODPROBE,;t t
+s,@LEX@,$LEX,;t t
+s,@PATH_LEX@,$PATH_LEX,;t t
+s,@YACC@,$YACC,;t t
+s,@PATH_YACC@,$PATH_YACC,;t t
+s,@RANLIB@,$RANLIB,;t t
+s,@PATH_RANLIB@,$PATH_RANLIB,;t t
+s,@RPCGEN@,$RPCGEN,;t t
+s,@PATH_RPCGEN@,$PATH_RPCGEN,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -4927,7 +5316,6 @@ s,@HAVE_LDAP@,$HAVE_LDAP,;t t
 s,@LIBLDAP@,$LIBLDAP,;t t
 s,@DAEMON_CFLAGS@,$DAEMON_CFLAGS,;t t
 s,@DAEMON_LDFLAGS@,$DAEMON_LDFLAGS,;t t
-s,@initdir@,$initdir,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
