- initial merge of Jeffs SASL auth code.   - entirely untest as yet. - re-work LDAP to use configurable defaults. - updated configure to check for libxml2 - required by SASL code. - updated configure to provide optional inclusion of SASL auth.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS initdir confdir mapdir DMALLOCLIB MOUNT HAVE_MOUNT UMOUNT HAVE_UMOUNT E2FSCK HAVE_E2FSCK E3FSCK HAVE_E3FSCK MODPROBE HAVE_MODPROBE LEX PATH_LEX YACC PATH_YACC RANLIB PATH_RANLIB RPCGEN PATH_RPCGEN CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBNSL LIBRESOLV HAVE_HESIOD LIBHESIOD HESIOD_FLAGS CPP EGREP HAVE_NISPLUS LDAP_FLAGS HAVE_LDAP LIBLDAP DAEMON_CFLAGS DAEMON_LDFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS initdir confdir mapdir DMALLOCLIB MOUNT HAVE_MOUNT UMOUNT HAVE_UMOUNT E2FSCK HAVE_E2FSCK E3FSCK HAVE_E3FSCK MODPROBE HAVE_MODPROBE LEX PATH_LEX YACC PATH_YACC RANLIB PATH_RANLIB RPCGEN PATH_RPCGEN XML_CONFIG CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBNSL LIBRESOLV HAVE_HESIOD LIBHESIOD HESIOD_FLAGS CPP EGREP HAVE_NISPLUS LDAP_FLAGS HAVE_LDAP LIBLDAP XML_FLAGS XML_LIBS SASL_FLAGS HAVE_SASL LIBSASL DAEMON_CFLAGS DAEMON_LDFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -853,6 +853,7 @@ Optional Packages:
 			  http://www.dmalloc.com/dmalloc.tar.gz
   --with-hesiod=DIR	  enable Hesiod support (libs and includes in DIR)
   --with-openldap=DIR	  enable OpenLDAP map support (libs and includes in DIR)
+  --with-sasl=DIR	  enable SASL support for LDAP maps (libs and includes in DIR)
 
 Some influential environment variables:
   CC          C compiler command
@@ -1968,6 +1969,67 @@ echo "${ECHO_T}yes" >&6
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
   fi
+fi
+
+# LDAP SASL auth need libxml
+for ac_prog in xml2-config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XML_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XML_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XML_CONFIG="$XML_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XML_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+XML_CONFIG=$ac_cv_path_XML_CONFIG
+
+if test -n "$XML_CONFIG"; then
+  echo "$as_me:$LINENO: result: $XML_CONFIG" >&5
+echo "${ECHO_T}$XML_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$XML_CONFIG" && break
+done
+test -n "$XML_CONFIG" || XML_CONFIG="no"
+
+echo "$as_me:$LINENO: checking for libxml2" >&5
+echo $ECHO_N "checking for libxml2... $ECHO_C" >&6
+if test "$XML_CONFIG" = "no"
+then
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  HAVE_LIBXML=0
+else
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  HAVE_LIBXML=1
+  XML_LIBS=`$XML_CONFIG --libs`
+  XML_FLAGS=`$XML_CONFIG --cflags`
 fi
 
 #
@@ -3882,6 +3944,120 @@ fi
 LDFLAGS="${AF_tmp_ldflags}"
 
 #
+# SASL support
+#   configure magic taken from:
+#	http://www.timof.qipc.org/autofs/autofs-4.1.4-ldap-20050930.patch
+#
+
+AF_tmp_ldflags="$LDFLAGS"
+LIBSASL=''
+HAVE_SASL=''
+
+# Check whether --with-sasl or --without-sasl was given.
+if test "${with_sasl+set}" = set; then
+  withval="$with_sasl"
+  if test "$withval" = 'no'; then
+		HAVE_SASL=0     # Disable
+	elif test -z "$withval" -o "$withval" = 'yes'
+	then
+		: Search for SASL in normal directory path
+	else
+		: Search for SASL in specific directory
+		HAVE_SASL=1
+		LDFLAGS="$LDFLAGS -L${withval}/lib"
+		LIBSASL="-L${withval}/lib"
+		SASL_FLAGS="-I${withval}/include"
+	fi
+
+fi;
+if test -z "$HAVE_SASL" -a "$HAVE_LIBXML" == "1"
+then
+	HAVE_SASL=0
+	echo "$as_me:$LINENO: checking for sasl_client_start in -lsasl2" >&5
+echo $ECHO_N "checking for sasl_client_start in -lsasl2... $ECHO_C" >&6
+if test "${ac_cv_lib_sasl2_sasl_client_start+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsasl2 -lsasl2 $LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sasl_client_start ();
+int
+main ()
+{
+sasl_client_start ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_sasl2_sasl_client_start=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_sasl2_sasl_client_start=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_sasl2_sasl_client_start" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl2_sasl_client_start" >&6
+if test $ac_cv_lib_sasl2_sasl_client_start = yes; then
+  HAVE_SASL=1 LIBSASL="$LIBSASL -lsasl2"
+fi
+
+	if test "$HAVE_SASL" == "1"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define WITH_SASL 1
+_ACEOF
+
+	fi
+fi
+
+
+
+
+
+
+LDFLAGS="${AF_tmp_ldflags}"
+
+#
 # Does gcc support building position independent executables?
 #
 ac_ext=c
@@ -5296,6 +5472,7 @@ s,@RANLIB@,$RANLIB,;t t
 s,@PATH_RANLIB@,$PATH_RANLIB,;t t
 s,@RPCGEN@,$RPCGEN,;t t
 s,@PATH_RPCGEN@,$PATH_RPCGEN,;t t
+s,@XML_CONFIG@,$XML_CONFIG,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -5314,6 +5491,11 @@ s,@HAVE_NISPLUS@,$HAVE_NISPLUS,;t t
 s,@LDAP_FLAGS@,$LDAP_FLAGS,;t t
 s,@HAVE_LDAP@,$HAVE_LDAP,;t t
 s,@LIBLDAP@,$LIBLDAP,;t t
+s,@XML_FLAGS@,$XML_FLAGS,;t t
+s,@XML_LIBS@,$XML_LIBS,;t t
+s,@SASL_FLAGS@,$SASL_FLAGS,;t t
+s,@HAVE_SASL@,$HAVE_SASL,;t t
+s,@LIBSASL@,$LIBSASL,;t t
 s,@DAEMON_CFLAGS@,$DAEMON_CFLAGS,;t t
 s,@DAEMON_LDFLAGS@,$DAEMON_LDFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
